### ISSUE TITLE
AddOn umbenennen  zu FOR Security?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/security#10]
1. wegen markenrechtlicher Bedenken
2. weil FOR security genau das sagt was es ist

**Comment by tbaddade** [comment]
Nicht das jetzt alle AddOns mit `for_` beginnen. 
Emfinde das schon suboptimal beim `for_sa11y` AddOn. 

Warum nicht einfach `security`?

**Comment by dergel** [comment]
würde dnan aber als key "Security" nehmen

**Comment by dergel** [comment]
Aber als Titel kann man gerne "FOR Security" nehmen. Security klingt so trocken.
